# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_merge_20190319_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(default='profile_pics/anon.png', upload_to='profile_pics'),
        ),
    ]
